# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='viewable_by_friends',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
