# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 00:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20161127_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grouptask',
            name='assignee',
            field=models.ManyToManyField(related_name='assignedTo', to=settings.AUTH_USER_MODEL),
        ),
    ]
