# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_habit_viewable_by_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='viewable_by_friends',
            field=models.BooleanField(default=True),
        ),
    ]
