# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20161127_1617'),
        ('todolist', '0003_auto_20161127_1630'),
    ]

    operations = [
    ]
