# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_merge_20161127_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='parent',
        ),
        migrations.RenameField(
            model_name='grouptask',
            old_name='assignee',
            new_name='assignees',
        ),
        migrations.AddField(
            model_name='grouptask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grouptask',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grouptask',
            name='duedate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskp',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
