# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_auto_20161128_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskp',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
