# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_taskp_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskp',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
