# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_auto_20161203_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='tasks',
        ),
        migrations.AddField(
            model_name='grouptask',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todolist.Group'),
            preserve_default=False,
        ),
    ]
