# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 22:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_auto_20161203_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='grouptask',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assignedTo', to=settings.AUTH_USER_MODEL),
        ),
    ]
