# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_auto_20161205_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskp',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
